### PR TITLE
Changed date attributes type from date-time to a new custom one.

### PR DESCRIPTION
**Pull request by razielgn**
In json-schema vocabulary, `date-time` means RFC 3339 (i.e. `2014-03-02T01:02:03+03:04`). This is just too restrictive for timezone-less dates, because it'd involve adding a time component and a timezone.

Timezone-less dates now should get correctly serialized as ISO 8601 (i.e. `2014-03-02`). No more awkwardly appending `T00:00:00Z` to dates.

### CODE REVIEW

**Comment by a2800276** [comment]
Unfortunately, dates without timezones are entirely useless because they don't really say anything about the point in time. Birthdate I can live with, but if we don't know the TZ of collection date, we don't know when to execute it. What's the problem with adding a default timezone to those dates that you're not sure about (for whatever reason)?

**Comment by razielgn** [comment]
We just don't have that information in the first place. Whatever timezone we add can potentially be wrong.

**Comment by a2800276** [comment]
So instead you would like the API consumer to guess (potentially incorrectly) the timezone? And this would only perpetuate the problem, as some of these fields are user input, where we would have to guess EVERY time we receive data and guess at how every individual client thinks that that the field is intended to be used.

**Comment by razielgn** [comment]
No guessing, those dates just don't have time zone information. They'll have to deal with it, nobody can make it up. It is implied that, without representing an exact point in time, they can't be used for comparisons of any kind.

**Comment by igorkosta** [comment]
@a2800276 Tim, it's not very productive to just close a PR :) 
Unfortunately we have to deal with the `date`s without timezone. If you have a solution proposal, you're very welcome to bring it up.
Cheers

**Comment by a2800276** [comment]
Concrete Proposal: 

- birthdate: assume UTC
- id_card_valid_until: assume UTC
- all other dates: use the actual timezone which we should know

sorry about closing the PR.

**Pull request closed without merging**
